from flask import Flask, request
app = Flask(__name__)
@app.route("/")
def hello_world():
    return 'Hello! This is Final Lab DevNet Associate !!!'

if __name == '__main__':
    app.run(host='0.0.0.0')
